import React, { useState } from 'react'
import { useLab } from '../lib/store.jsx'
import { WIDGETS } from '../widgets/registry.js'
import { getCorrectKey } from './Questions.jsx'
import { BINGO_SQUARES, bingoLines } from './BingoDrawer.jsx'

// End-of-lab results screen. Students download a file here and upload it to
// Canvas, so the file has to stand on its own: who, when, what they answered,
// whether it was right, and the game scores the widgets recorded.

function collect({ answers, predictions, runData, bingo }) {
  const modules = []
  let scored = 0
  let correctCount = 0
  let answeredCount = 0

  for (const w of WIDGETS) {
    const rows = []
    if (w.predict) {
      const p = predictions[w.id]
      rows.push({
        kind: 'prediction',
        label: `${w.label}-P`,
        question: w.predict.text,
        answer: p ? (w.predict.options.find((o) => o.key === p)?.label || p) : '(not made)',
        correct: 'N/A',
      })
    }
    w.questions.forEach((q, qi) => {
      const chosen = answers[w.id]?.[q.id]
      const chosenLabel = q.options.find((o) => o.key === chosen)?.label || ''
      const key = getCorrectKey(q, runData[w.id])
      let correct = 'N/A'
      if (chosen) {
        answeredCount++
        if (key) {
          scored++
          correct = chosen === key ? 'YES' : 'NO'
          if (chosen === key) correctCount++
        }
      }
      rows.push({
        kind: 'question',
        label: q.rowLabel || `${w.label}-Q${qi + 1}`,
        question: q.text,
        answer: chosen ? chosenLabel : '(not answered)',
        correct,
      })
    })
    modules.push({ label: w.label, title: w.title, section: w.section, rows })
  }

  // Game results the widgets stashed in runData.
  const d = runData
  const games = []
  if (d.w3?.sortScore != null) games.push(`Citation Sort (W3): ${d.w3.sortScore} of 6 sorted correctly`)
  if (d.w5?.solvedWith) {
    games.push(`Prompt Golf (W5/W6): solved with ${d.w5.solvedWith.techniques.length} technique(s) ` +
      `in ${d.w5.solvedWith.strokes} run(s) [${d.w5.solvedWith.techniques.join(', ')}]`)
  } else if (d.w5?.strokes) {
    games.push(`Prompt Golf (W5/W6): ${d.w5.strokes} run(s), not solved to zero`)
  }
  if (d.w5?.baselineMismatches != null) games.push(`  baseline out-of-statute numbers: ${d.w5.baselineMismatches}`)
  if (d.ttl?.score != null) games.push(`Two Truths and a Lie: ${d.ttl.score} of 6, best streak ${d.ttl.streak ?? 0}`)
  if (d.w9?.score != null) games.push(`Pronoun prediction (W9): called ${d.w9.score} of 10 correctly`)
  if (d.w14?.score != null) games.push(`Spot the Fake (W14): ${d.w14.score} of 6, best streak ${d.w14.streak ?? 0}`)
  if (d.w12?.ceoShare != null) games.push(`Picture the Job (W12): CEO grid tallied ${Math.round(d.w12.ceoShare * 100)}% presenting male`)
  if (d.fc?.caught) {
    const total = Object.values(d.fc.caught).reduce((a, b) => a + b, 0)
    games.push(`Fact-Check Challenge: ${total} planted errors caught across the three drafts`)
  }
  const claimed = Object.keys(bingo).length
  if (claimed) {
    games.push(`Hallucination Bingo: ${claimed} of 16 squares, ${bingoLines(bingo)} bingo(s)`)
  }

  return { modules, scored, correctCount, answeredCount, games, claimed }
}

function buildTxt(data, name) {
  const { modules, scored, correctCount, answeredCount, games } = data
  const L = []
  L.push('BARRY UNIVERSITY | AI FUNDAMENTALS AND EXPERIMENTATION')
  L.push('WEEK 4 THURSDAY LAB | HALLUCINATION LAB RESULTS')
  L.push('='.repeat(62))
  L.push(`Student: ${name || '(no name entered)'}`)
  L.push(`Completed: ${new Date().toLocaleString()}`)
  L.push(`Questions answered: ${answeredCount}`)
  L.push(`Scored correct: ${correctCount} of ${scored} auto-scored questions`)
  L.push('')
  if (games.length) {
    L.push('GAME AND EXPERIMENT RESULTS')
    L.push('-'.repeat(62))
    games.forEach((g) => L.push(g))
    L.push('')
  }
  L.push('DETAILED RESPONSES')
  L.push('-'.repeat(62))
  for (const m of modules) {
    L.push('')
    L.push(`${m.label}. ${m.title}   [${m.section}]`)
    for (const r of m.rows) {
      if (r.kind === 'prediction') {
        L.push(`  Prediction: ${r.answer}`)
        L.push(`     (asked: ${r.question})`)
      } else {
        L.push(`  ${r.label}. ${r.question}`)
        L.push(`     My answer: ${r.answer}`)
        L.push(`     Correct:   ${r.correct}`)
      }
    }
  }
  L.push('')
  L.push('='.repeat(62))
  L.push('Generated by the Hallucination Lab. Upload this file to Canvas.')
  return L.join('\n')
}

function buildCsv(data, name) {
  const esc = (v) => `"${String(v).replace(/"/g, '""')}"`
  const rows = [['Student', 'Row', 'Question', 'My Answer', 'Correct (Y/N)', 'One-sentence observation']]
  for (const m of data.modules) {
    for (const r of m.rows) {
      rows.push([name || '', r.label, r.question, r.answer,
        r.correct === 'YES' ? 'Y' : r.correct === 'NO' ? 'N' : '', ''])
    }
  }
  return rows.map((r) => r.map(esc).join(',')).join('\r\n')
}

function download(filename, text, mime) {
  const blob = new Blob([text], { type: `${mime};charset=utf-8` })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

function slug(name) {
  const s = (name || 'student').trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
  return s || 'student'
}

export default function ResultsPage() {
  const lab = useLab()
  const { studentName, setStudentName, setIndex } = lab
  const [downloaded, setDownloaded] = useState(null)
  const [copied, setCopied] = useState(false)
  const data = collect(lab)
  const stamp = new Date().toISOString().slice(0, 10)

  function downloadTxt() {
    download(`hallucination-lab-${slug(studentName)}-${stamp}.txt`,
      buildTxt(data, studentName), 'text/plain')
    setDownloaded('txt')
  }
  function downloadCsv() {
    download(`hallucination-lab-${slug(studentName)}-${stamp}.csv`,
      buildCsv(data, studentName), 'text/csv')
    setDownloaded('csv')
  }
  async function copyAll() {
    try {
      await navigator.clipboard.writeText(buildTxt(data, studentName))
      setCopied(true)
    } catch {
      window.prompt('Copy this text manually:', buildTxt(data, studentName))
    }
  }

  return (
    <div>
      <h1>Download your results</h1>

      <div className="card">
        <p><strong>You are done. Two steps left:</strong></p>
        <ol>
          <li>Put your name in the box below so your instructor knows whose file this is.</li>
          <li>Click <strong>Download my results</strong>, then upload that file to the Week 4 assignment in Canvas.</li>
        </ol>
        <p className="error-note">
          Nothing is submitted automatically. If you close this tab without downloading, your work is gone.
        </p>
      </div>

      <label className="field-label" htmlFor="results-name">Your name (first and last)</label>
      <input
        id="results-name"
        type="text"
        value={studentName}
        placeholder="e.g. Maria Gonzalez"
        onChange={(e) => setStudentName(e.target.value)}
        style={{ width: 340 }}
      />
      {!studentName.trim() && (
        <p className="muted">Add your name before downloading, or the file will be marked "(no name entered)".</p>
      )}

      <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', margin: '18px 0' }}>
        <button className="btn-primary" onClick={downloadTxt} style={{ fontSize: '1.05em', padding: '12px 22px' }}>
          Download my results (.txt)
        </button>
        <button onClick={downloadCsv}>Download as spreadsheet (.csv)</button>
        <button onClick={copyAll}>{copied ? 'Copied' : 'Copy to clipboard instead'}</button>
      </div>
      {downloaded && (
        <p className="explain" aria-live="polite">
          <strong>Downloaded.</strong> Look in your Downloads folder for a file starting with
          {' '}<code>hallucination-lab-{slug(studentName)}</code>. Upload that file to Canvas now.
        </p>
      )}

      <div className="card">
        <p className="golf-score">
          Scored {data.correctCount} of {data.scored} auto-scored questions.
          {' '}{data.answeredCount} questions answered in total.
        </p>
        {data.games.length > 0 && (
          <ul>{data.games.map((g, i) => <li key={i}>{g}</li>)}</ul>
        )}
      </div>

      <h2>Everything in your file</h2>
      <table className="summary-table">
        <thead>
          <tr><th>Row</th><th>Question</th><th>My answer</th><th>Correct</th></tr>
        </thead>
        <tbody>
          {data.modules.flatMap((m) =>
            m.rows.map((r) => (
              <tr key={`${m.label}-${r.label}-${r.kind}`}>
                <td>{r.label}</td>
                <td>{r.question}</td>
                <td>{r.answer}</td>
                <td className={r.correct === 'YES' ? 'correct-yes' : r.correct === 'NO' ? 'correct-no' : ''}>
                  {r.correct === 'N/A' ? '' : r.correct}
                </td>
              </tr>
            ))
          )}
        </tbody>
      </table>

      <div className="nav-row">
        <button onClick={() => setIndex(WIDGETS.length - 1)}>Back to the last module</button>
      </div>
    </div>
  )
}
